[tool.poetry]
name = "python4parser"
version = "0.1.0"
description = ""
authors = ["asadulaev-yu <asadulaev.yu@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
